version: x.x.{build}
image: Visual Studio 2017
configuration: Release
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: dnSpy.sln
  parallel: true
  verbosity: normal
artifacts:
- path: dnSpy/dnSpy/bin
  name: dnSpy
notifications:
- provider: Email
  to:
  - appveyor@lesderid.net
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
